[package]
name = "gust"
version = "0.1.0"
authors = ["sum12 <sum12@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
